---
- name: install ruby
  apt: name=ruby-full state=present

- name: install sass
  gem: name=sass state=present
  become: yes
  become_user: vagrant

- name: get gem directory
  shell: ruby -e 'print Gem.user_dir'
  register: gem_dir
  become: true
  become_user: vagrant

- name: symlink sass
  file: src={{ item }}/bin/sass dest=/usr/local/bin/sass owner=vagrant group=vagrant mode=0755 state=link
  with_items: "{{ gem_dir.stdout }}"
