---
- name: install nodejs
  apt: name=nodejs state=present

- name: symlink node and nodejs
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

- name: install npm
  apt: name=npm state=present

- name: install build essential
  apt: name=build-essential state=present

- name: fetch yarn pub key
  apt_key: url=http://dl.yarnpkg.com/debian/pubkey.gpg state=present

- name: add yarn source list
  template: src=roles/nodejs/templates/yarn.list.j2 dest=/etc/apt/sources.list.d/yarn.list

- name: refresh apt cache
  apt: update_cache=yes

- name: install yarn
  apt: name=yarn state=present
