- hosts: all
  become: true
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: refresh apt cache
      apt: update_cache=yes
  roles:
    - system
    - ntp
    - php
    - composer
    - nginx
    - apache
    - mariadb
    - ruby
    - nodejs
    - dotfiles
