- hosts: all
  become: true
  become_method: sudo
  gather_facts: no
  roles:
    - system
    - apt
    - ntp
    - ssl
    - php
    - composer
    - nginx
    - apache
    # - mariadb
    - mysql
    - ruby
    - nodejs
    - dotfiles
    - tools
